common:
  autoBackupData: false
  infinityTimer: false
  infinityTimerLegacy: false
  disableMask: false
  disableBackground: false
  showFPS: false
  singlePlayer: 
    enable: false
    hideSubMonitor: false
  forceQuickRetry: false
  forwardATouchRegionToButton: false
  skipFade: false
  skipWarningScreen: false
  quickBoot: false
  blockCoin: false
  ignoreAnyGameInformation: false
  changeDefaultOption: false
  changeFadeStyle: false
  networkLogger:
    enable: false
    printToConsole: false
  customVersionText:
    enable: false
    versionText: ""
  dummyLogin:
    enable: false
    defaultUserId: 0
  customCameraId:
    enable: false
    chimeCameraId: 0
    leftQrCameraId: 0
    rightQrCameraId: 0
    photoCameraId: 0
  changeGameSettings:
    enable: false
    codeRead: false
    iconPhoto: false
    uploadPhoto: false
    charaSelect: false
    
cheat:
  autoPlay: false
  fastSkip: false
  chartController: false
  allCollection: false
  unlockEvent: false
  unlockMusic:
    enable: false
    saveToUserData: false
  unlockMaster:
    enable: false
    saveToUserData: false
  unlockUtage:
    enable: false
    unlockDoublePlayerMusic: false
  resetLoginBonusRecord: false
  forceCurrentIsBest: false
  setAllCharacterAsSameAndLock: false
  rewriteLoginBonusStamp: 
    enable: false 
    point: 0

fix:
  disableEnvironmentCheck: false
  disableEncryption: false
  disableReboot: false
  disableIniClear: false
  fixDebugInput: false
  fixCheckAuth: false
  forceAsServer: false
  skipCakeHashCheck: false
  skipSpecialNumCheck: false
  skipVersionCheck: false
  restoreCertificateValidation: false
  rewriteNoteJudgeTiming:
    enable: false
    adjustTiming: 0.0
    judgeTiming: 0.0

modSetting:
  safeMode: false
  showInfo: false
  showPanel: false
  logUnity: false
