common:
  infinityTimer: false
  disableMask: false
  disableBackground: false
  showFPS: false
  singlePlayer: 
    enable: false
    hideSubMonitor: false
  forceQuickRetry: false
  forwardATouchRegionToButton: false
  skipFade: false
  skipWarningScreen: false
  quickBoot: false
  blockCoin: false
  ignoreAnyGameInformation: false
  changeDefaultOption: false
  changeFadeStyle: false
  networkLogger:
    enable: false
    printToConsole: false
  customVersionText:
    enable: false
    versionText: ""
  dummyLogin:
    enable: false
    defaultUserId: 0
  customCameraId:
    enable: false
    chimeCameraId: 0
    leftQrCameraId: 0
    rightQrCameraId: 0
    photoCameraId: 0
  changeGameSettings:
    enable: false
    codeRead: false
    iconPhoto: false
    uploadPhoto: false
    charaSelect: false
    

cheat:
  autoPlay: false
  fastSkip: false
  chartTimer: false
  allCollection: false
  unlockMusic: false
  unlockMaster: false
  unlockEvent: false
  resetLoginBonusRecord: false
  forceCurrentIsBest: false
  setAllCharacterAsSameAndLock: false
  rewriteLoginBonusStamp: 
    enable: false 
    point: 0

fix:
  disableEncryption: false
  disableReboot: false
  skipVersionCheck: false
  rewriteNoteJudgeTiming:
    enable: false
    adjustTiming: 0.0
    judgeTiming: 0.0

modSetting:
  showInfo: false
  showPanel: false
  forceIsChinaBuild: false
  safeMode: false
