china:
  dummyLogin:
    enable: false
    defaultUserId: 0
  customCameraId: 
    enable : false
    qrCameraId: 0
    photoCameraId: 0
 
common:
  infinityTimer: false
  disableMask: false
  showFPS: false
  singlePlayer: 
    enable: false
    hideSubMonitor: false
  forwardATouchRegionToButton: false
  skipWarningScreen: false
  quickBoot: false
  blockCoin: false
  ignoreAnyGameInformation: false
  changeDefaultOption: false
  networkLogger:
    enable: false
    printToConsole: false
  customVersionText:
    enable: false
    versionText: ""

cheat:
  autoPlay: false
  fastSkip: false
  chartTimer: false
  allCollection: false
  unlockMusic: false
  unlockMaster: false
  unlockEvent: false
  resetLoginBonusRecord: false
  forceCurrentIsBest: false
  setAllCharacterAsSameAndLock: false

fix:
  disableEncryption: false
  disableReboot: false
  skipVersionCheck: false
  rewriteNoteJudgeTiming:
    enable: false
    adjustTiming: 0.0
    judgeTiming: 0.0

modSetting:
  showInfo: false
  showPanel: false
  forceIsChinaBuild: false
  safeMode: false
